# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "434f338d86d13f8b88edf2c88bda32df"
name = "b2b-variant-aggregate"
handle = "b2b-variant-aggregate"
application_url = "https://howard-particular-satisfy-coral.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://howard-particular-satisfy-coral.trycloudflare.com/auth/callback", "https://howard-particular-satisfy-coral.trycloudflare.com/auth/shopify/callback", "https://howard-particular-satisfy-coral.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
