api_version = "2025-04"

[[extensions]]
name = "B2B Variant Aggregate Discount"
handle = "b2b-variant-aggregate-discount"
type = "function"
description = "Aggregate qty across variants of a product and enforce tier price (B2B only)."

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
